---
site_name: "KBase Credit Engine Metadata Schema"
theme:
  name: material
  palette:
   scheme: slate
   primary: light blue
   accent: light blue
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2
nav:
  - Index: index.md
  - GitHub Repo: https://github.com/kbase/credit_engine
#  - KBase DOIs: docs/kbase_dois.md

site_url: https://kbase.github.io/credit_engine
repo_url: https://github.com/kbase/credit_engine

# Uncomment this block to enable use of Google Analytics.
# Replace the property value with your own ID.
# extra:
#   analytics:
#     provider: google
#     property: G-XXXXXXXXXX
