[tool.poetry]
name = "credit_engine"
version = "0.1.0"
description = ""
authors = ["ialarmedalien <ialarmedalien@gmail.com>"]
packages = [
    { include = 'credit_engine' }
]

[tool.poetry.dependencies]
json2python-models = "^0.3.0"
linkml = "^1.4.8"
linkml-runtime = "^1.4.9"
pydantic = "^1.10.6"
pytest = "^7.2.2"
pytest-cases = "^3.6.14"
python = "^3.9"
requests = "^2.28.2"
xmlschema = "^2.2.2"
xsdata = {extras = ["cli", "lxml", "soap"], version = "^22.12"}

[tool.poetry.dev-dependencies]
black = "^23.3.0"
darglint = "^1.8.1"
dlint = "^0.14.0"
flake8-bandit = "^4.1.1"
flake8-bugbear = "^23.3.12"
flake8-builtins = "^2.1.0"
flake8-comprehensions = "^3.11.1"
flake8-docstrings = "^1.7.0"
flake8-eradicate = "^1.4.0"
flake8-pie = "^0.16.0"
flake8-return = "^1.2.0"
flake8-simplify = "^0.20.0"
isort = "^5.12.0"
pytest-cov = "^4.0.0"
pytest-sugar = "^0.9.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
skip_gitignore = true
