[tool.isort]
profile = "black"
skip_gitignore = true

[tool.poetry]
name = "credit_engine"
version = "0.1.0"
description = ""
authors = ["ialarmedalien <ialarmedalien@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
linkml = "^1.2.13"
linkml-runtime = "^1.3.1"
crossrefapi = "^1.5.0"
crossref-commons = "^0.0.7"
pydantic = "^1.9.2"
requests = "^2.28.0"
xsdata = {extras = ["cli", "lxml", "soap"], version = "^22.7"}
xmlschema = "^2.0.1"
pytest = "^7.1.2"

[tool.poetry.dev-dependencies]
black = "^22.8.0"
flake8-bugbear = "^22.4.25"
flake8-pie = "^0.15.0"
flake8-builtins = "^1.5.3"
flake8-return = "^1.1.3"
flake8-bandit = "^3.0.0"
flake8-comprehensions = "^3.10.0"
flake8-eradicate = "^1.2.1"
dlint = "^0.13.0"
isort = "^5.10.1"
darglint = "^1.8.1"
flake8-docstrings = "^1.6.0"
flake8-simplify = "^0.19.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
