[tool.poetry]
name = "credit_engine"
version = "0.1.0"
description = ""
authors = ["ialarmedalien <ialarmedalien@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
linkml = "^1.2.13"
crossrefapi = "^1.5.0"
requests = "^2.28.0"
black = "^22.3.0"
flake8-bugbear = "^22.4.25"
flake8-pie = "^0.15.0"
flake8-builtins = "^1.5.3"
flake8-return = "^1.1.3"
flake8-bandit = "^3.0.0"
flake8-comprehensions = "^3.10.0"
flake8-eradicate = "^1.2.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
