[tool.poetry]
name = "credit_engine"
version = "0.1.0"
description = ""
authors = ["ialarmedalien <ialarmedalien@gmail.com>"]
packages = [
    { include = 'credit_engine' }
]

[tool.poetry.dependencies]
python = "^3.9"
json2python-models = "^0.2.7"
pydantic = "^1.10.2"
pytest = "^7.1.3"
requests = "^2.28.0"
xsdata = {extras = ["cli", "lxml", "soap"], version = "^22.7"}
xmlschema = "^2.0.4"
pytest-cases = "^3.6.13"
linkml = "^1.3.5"
linkml-runtime = "^1.3.2"

[tool.poetry.dev-dependencies]
black = "^22.8.0"
darglint = "^1.8.1"
dlint = "^0.13.0"
flake8-bandit = "^4.1.1"
flake8-bugbear = "^22.9.11"
flake8-builtins = "^1.5.3"
flake8-comprehensions = "^3.10.0"
flake8-docstrings = "^1.6.0"
flake8-eradicate = "^1.3.0"
flake8-pie = "^0.16.0"
flake8-return = "^1.1.3"
flake8-simplify = "^0.19.3"
isort = "^5.10.1"
pytest-cov = "^4.0.0"
pytest-sugar = "^0.9.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
skip_gitignore = true
