name: Python autoformatting

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v3
      -
        uses: psf/black@stable
        with:
          options: --verbose

      -
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto-commit black formatting changes
