---
name: Auto-deployment of credit_engine Documentation
on:
  push:
    branches: [main, develop]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Poetry.
        uses: snok/install-poetry@v1

      - name: Install dependencies.
        run: poetry install -E docs

      - name: Build documentation.
        run: |
          mkdir -p docs
          touch docs/.nojekyll
          poetry run gen-doc -d docs schema/kbase/linkml/credit_metadata.yaml
          poetry run mkdocs gh-deploy
