name: Standard PR workflow

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review

jobs:
  format_files:
    uses: ./.github/workflows/black.yaml

  run_unit_tests:
    uses: ./.github/workflows/run_tests.yaml
    needs: format_files

  run_code_ql:
    uses: ./.github/workflows/codeql.yaml

  run_codacy:
    uses: ./.github/workflows/codacy.yaml

  run_trivy:
    uses: ./.github/workflows/trivy.yaml
